### ISSUE TITLE
运行main.py 报错

### ISSUE THREAD

**Issue by RealCole** [EdisonLeeeee/SpikeNet#2]
你好！我根据readme运行了这个指令
![image](https://user-images.githubusercontent.com/62944585/227190915-3587598a-4db8-4a85-92bd-a97538407cef.png)
然后再运行main.py却报错了。
![image](https://user-images.githubusercontent.com/62944585/227191023-51e82768-8e6f-4434-a8e5-b0e94fc9ced8.png)
然后我看了下目录结构
![image](https://user-images.githubusercontent.com/62944585/227191893-525ecc3b-2428-4ea0-9fcc-36368e6db04f.png)
确实没有生成这个sample_neighber文件 而是sample_neighber.egg-info
请问是什么原因、如何解决呢？

**Comment by RealCole** [comment]
> > 你好！我根据readme运行了这个指令 ![image](https://user-images.githubusercontent.com/62944585/227190915-3587598a-4db8-4a85-92bd-a97538407cef.png) 然后再运行main.py却报错了。 ![image](https://user-images.githubusercontent.com/62944585/227191023-51e82768-8e6f-4434-a8e5-b0e94fc9ced8.png) 然后我看了下目录结构
![image](https://user-images.githubusercontent.com/62944585/227191719-e170efbf-5070-4e9c-b145-99116a61a010.png)

> > 确实没有生成这个sample_neighber文件 而是sample_neighber.egg-info 请问是什么原因、如何解决呢？

**Comment by EdisonLeeeee** [comment]
抱歉前几天有事未能及时回复！

这种情况下可能是运行`python setup.py install`之后未能编译成功。请问您可以再运行一次然后查看一下运行log吗？

**Comment by RealCole** [comment]
> 抱歉前几天有事未能及时回复！
> 
> 这种情况下可能是运行`python setup.py install`之后未能编译成功。请问您可以再运行一次然后查看一下运行log吗？

没事！十分感谢您的回复！好的，下面是运行log（会比较长，所以我分开部分截图了）
![image](https://user-images.githubusercontent.com/62944585/228147390-d7dbf486-ff09-4f50-a6d8-bbc46696f2c8.png)
![image](https://user-images.githubusercontent.com/62944585/228147544-388e0812-ccb7-4c85-b3a9-654e95c6609d.png)
中间省略了一大堆类似的log日志。。
![image](https://user-images.githubusercontent.com/62944585/228147847-14f22190-8daa-4ad0-b8e0-af2647c07107.png)
然后这是运行python setup.py install之后的项目目录
![image](https://user-images.githubusercontent.com/62944585/228148046-7d6a32a3-f669-4b0e-af20-929c42681365.png)
劳烦您看一下问题出在哪了？

**Comment by EdisonLeeeee** [comment]
抱歉，从您目前的log来看安装是没问题的，我也暂时找不到出错的原因，但是我可以给您一个[编译好的whl](https://github.com/EdisonLeeeee/SpikeNet/blob/master/sample_neighber-0.0.0-cp39-cp39-win_amd64.whl)文件以供您下载后直接安装。

**Comment by EdisonLeeeee** [comment]
抱歉，从您目前的log来看安装是没问题的，我也暂时找不到出错的原因，但是我可以给您一个[编译好的whl](https://github.com/EdisonLeeeee/SpikeNet/blob/master/sample_neighber-0.0.0-cp39-cp39-win_amd64.whl)文件以供您下载后直接安装。

**Comment by RealCole** [comment]
> 抱歉，从您目前的log来看安装是没问题的，我也暂时找不到出错的原因，但是我可以给您一个[编译好的whl](https://github.com/EdisonLeeeee/SpikeNet/blob/master/sample_neighber-0.0.0-cp39-cp39-win_amd64.whl)文件以供您下载后直接安装。

万分感激！我找到问题所在了！祝您科研和生活都能一帆风顺！

**Comment by welcomeyou2019** [comment]
> > 抱歉，从您目前的log来看安装是没问题的，我也暂时找不到出错的原因，但是我可以给您一个[编译好的whl](https://github.com/EdisonLeeeee/SpikeNet/blob/master/sample_neighber-0.0.0-cp39-cp39-win_amd64.whl)文件以供您下载后直接安装。
> 
> 万分感激！我找到问题所在了！祝您科研和生活都能一帆风顺！

你好，请问你是怎么解决这个问题的啊，我也遇到了相同的问题

**Comment by RealCole** [comment]
> 

我是环境问题，我把相关配置安装在了另一个环境，忘记切换了，切换回来就好了

**Comment by welcomeyou2019** [comment]
好的，多谢多谢

**Comment by welcomeyou2019** [comment]
请问可以提供一下tmall.npy 和patent.npy两个源文件吗，多谢

**Comment by EdisonLeeeee** [comment]
您好，感谢您对该工作的关注。tmall和patent的数据集已经通过阿里云盘分享，链接如下：
https://www.aliyundrive.com/s/LH9qa9XZmXa

注：由于阿里云盘不支持直接分享npy文件，因此下载后需要手动修改后缀名为.npy。
