### ISSUE TITLE
测试方式是否与其他baseline不同？

### ISSUE THREAD

**Issue by hmtbgc** [EdisonLeeeee/SpikeNet#3]
阅读代码后，我有一个疑问：
其他dynamic gnn 的实验是基于time stamp划分train valid test set，而SpikeNet似乎使用了所有的time stamp进行训练？如此比较是否不太公平。

**Comment by EdisonLeeeee** [comment]
感谢您对我们工作的关注。

为保证公平的比较，在测试过程中，所有baseline方法都采用和SpikeNet一样的实验设置，即利用所有time steps进行训练。

**Comment by hmtbgc** [comment]
谢谢你的回复，顺便问下，你们的算法可以修改成对时间步进行划分，也就是其他论文中的划分形式吗？因为我看代码中是划分节点的。

**Comment by EdisonLeeeee** [comment]
可以的，只需要在这一行修改模型仅对于数据集中前面部分的时间步的数据进行拟合即可：
https://github.com/EdisonLeeeee/SpikeNet/blob/681b8e508b73d4efbc5b144e76b1f52f3ff718ed/main.py#L65

例如
```python
for time_step in range(num_train_steps):
```
对前`num_train_steps`步长的数据进行学习得到节点表征
