### ISSUE TITLE
关于领域采样

### ISSUE THREAD

**Issue by inst15** [EdisonLeeeee/SpikeNet#5]
作者您好！您的文章使我深受启发！有个小小的问题，请问作者在领域采样的环节是否应用了SpikeNet？

**Comment by PengpengShao** [comment]
哈喽，sample_neighber_cpu编译出来了吗

**Comment by EdisonLeeeee** [comment]
> 作者您好！您的文章使我深受启发！有个小小的问题，请问作者在领域采样的环节是否应用了SpikeNet？

您好！邻域采样属于SpikeNet的其中一部分，主要是对于当前时刻图快照的采样，以及相较于上一时刻快照新增子图的采样

**Comment by inst15** [comment]
感谢作者的回答！

**Comment by inst15** [comment]
@PengpengShao 编译出来了
