### ISSUE TITLE
sample_neighber_cpu

### ISSUE THREAD

**Issue by PengpengShao** [EdisonLeeeee/SpikeNet#6]

**Comment by EdisonLeeeee** [comment]
您好，编译好的whl文件在[这里](https://github.com/EdisonLeeeee/SpikeNet/blob/master/sample_neighber-0.0.0-cp39-cp39-win_amd64.whl)，环境为Windows，Python3.9

**Comment by PengpengShao** [comment]
哈喽，其实是from sample_neighber import sample_neighber_cpu这里出现问题，应该是没有sample_neighber.py文件把

**Comment by EdisonLeeeee** [comment]
sample_neighbor并不是Python文件导入的，是由`spikenet/sample_neighber.cpp`编译得到的模块，因此需要你首先运行`pip install .`编译才能导入

**Comment by PengpengShao** [comment]
pip install 啥呢？我执行python setup.py install以求获得这个，但始终获得不了。

**Comment by EdisonLeeeee** [comment]
`pip install .`

**Comment by PengpengShao** [comment]
感谢。搞定了
