### ISSUE TITLE
代码报错询问

### ISSUE THREAD

**Issue by ZeyuZhu0120** [EdisonLeeeee/SpikeNet#7]
作者您好，我在运行您下面这段命令的时候，代码发生了如下报错，请问该如何解决呢？非常期待您的回复！！
python main.py --dataset tmall --hids 512 10 --batch_size 1024 --p 1.0 --train_size 0.4

<img width="851" alt="image" src="https://github.com/EdisonLeeeee/SpikeNet/assets/91859784/98e1aad6-8daa-46e8-b856-819eb67c1a11">

**Comment by EdisonLeeeee** [comment]
您好，感谢您对我们工作的关注。关于您遇到的问题，原因应该是您没有提前进行预处理得到Tmall数据集的节点特征。原始数据集没有节点特征因此输出的`data.num_features`为`None`。

您需要手动运行代码生成节点特征或直接下载预处理好的节点特征，详见https://github.com/EdisonLeeeee/SpikeNet?tab=readme-ov-file#optional-re-generate-node-features-via-deepwalk

**Comment by ZeyuZhu0120** [comment]
非常感谢您的回复！！祝您科研顺利~
