### ISSUE TITLE
torch版本

### ISSUE THREAD

**Issue by yexinruyexinruyexinru** [EdisonLeeeee/SpikeNet#8]
您好，由于显卡算力的原因，需要将torch的版本提高一些，请问怎么调整才可以使项目适应torch1.12.0版本

**Comment by EdisonLeeeee** [comment]
您好，该项目代码与torch版本无关，更高版本的torch都可以兼容运行

**Comment by yexinruyexinruyexinru** [comment]
您好，非常感谢您的回答。我在尝试高版本torch时出现了以下问题。尝试过一些方法后并没有成功解决，请问您有什么解决思路吗？
Traceback (most recent call last):
  File "/home/users/yxr/SpikeNet-master/main.py", line 11, in <module>
    from spikenet.utils import (RandomWalkSampler, Sampler, add_selfloops,
  File "/home/users/yxr/SpikeNet-master/spikenet/utils.py", line 4, in <module>
    from sample_neighber import sample_neighber_cpu
ImportError: /home/users/yxr/SpikeNet-master/sample_neighber.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv
![Uploading WPS图片(1).png…]()

**Comment by yexinruyexinruyexinru** [comment]
我使用的GPU为A6000，cuda版本为12.2

**Comment by EdisonLeeeee** [comment]
您好，因为`sample_neighber_cpu`函数是依赖于编译的pytorch版本的，在您切换pytorch版本后需要重新编译该项目才可以运行。

**Comment by yexinruyexinruyexinru** [comment]
感谢您的回答。在您的启发下，排除torch版本的问题，重新配置了conda环境，目前已经成功运行项目
